name: calt-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h66e93f0_5
  - arpack=3.9.1=nompi_hf03ea27_102
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bdw-gc=8.2.8=h5888daf_2
  - beautifulsoup4=4.13.4=pyha770c72_0
  - beniget=0.4.2.post1=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.43=h4bf12b8_5
  - blas-devel=3.9.0=32_h1ea3ea9_openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py312h2ec8cdc_3
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - cddlib=1!0.94m=h9202a9a_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - cliquer=1.22=hd590300_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.9.0=pyh707e725_1
  - comm=0.2.2=pyhd8ed1ab_1
  - conda-gcc-specs=15.1.0=hc55bae6_3
  - contourpy=1.3.2=py312h68727a3_0
  - conway-polynomials=0.10=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - curl=8.14.1=h332b0f4_0
  - cvxopt=1.3.2=py312h9a1927c_4
  - cycler=0.12.1=pyhd8ed1ab_1
  - cypari2=2.2.2=py312hb7bab4f_0
  - cysignals=1.12.3=py312h2ec8cdc_0
  - cython=3.1.2=py312h2614dfc_2
  - debugpy=1.8.14=py312h2ec8cdc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - dsdp=5.8=hd9d9efa_1203
  - ecl=24.5.10=h75482ee_1
  - eclib=20250122=h513e007_1
  - ecm=7.0.6=h90cbb55_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fflas-ffpack=2.5.0=h4f9960b_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - flintqs=1.0=h85f3911_1001
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py312h178313f_0
  - fplll=5.5.0=hd20a173_0
  - fpylll=0.6.3=py312ha4ee43a_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - future=1.0.0=pyhd8ed1ab_2
  - gap-core=4.14.0=h3b03731_5
  - gap-defaults=4.14.0=ha770c72_5
  - gast=0.5.5=pyhd8ed1ab_0
  - gcc=15.1.0=h33e79ad_3
  - gcc_impl_linux-64=15.1.0=h4393ad2_3
  - gf2x=1.3.0=h55551d5_3
  - gfan=0.6.2=hb86e20a_1003
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_3
  - giac=1.9.0.21=hca478b9_3
  - giflib=5.2.2=hd590300_0
  - givaro=4.2.0=hb397f18_2
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312h7201bc8_0
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.7=he838d99_0
  - gxx=15.1.0=h33e79ad_3
  - gxx_impl_linux-64=15.1.0=h6a1bac1_3
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - igraph=0.10.16=h98b0679_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - iml=1.0.5=h623f65a_1004
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmol=14.32.10=ha770c72_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h7900ff3_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcalc=2.0.5=h9cf73fc_3
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_5
  - lerc=4.0.0=h0aef613_1
  - libamd=3.3.3=haaf9dc3_7100102
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbraiding=1.3.1=h5888daf_0
  - libbrial=1.2.12=h76af697_3
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcblas=3.9.0=32_he106b2a_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libcolamd=3.3.4=h32481e8_7100102
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflint=3.2.2=h754cb6e_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=15.1.0=h4c094af_103
  - libgcc-ng=15.1.0=h69a702a_3
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libhomfly=1.02r6=hd590300_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libklu=2.3.5=hf24d653_7100102
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblapacke=3.9.0=32_he2f377e_openblas
  - libldl=3.3.2=h32481e8_7100102
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libparu=1.0.0=h17147ab_7100102
  - libpng=1.6.49=h943b412_0
  - librbio=4.3.4=h32481e8_7100102
  - libsanitizer=15.1.0=h97b714f_3
  - libsodium=1.0.20=h4ab18f5_0
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_103
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libtiff=4.7.0=hf01ce69_5
  - libumfpack=6.3.5=heb53515_7100102
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - linbox=1.7.0=h0451620_2
  - lrcalc=2.1=h5888daf_7
  - m4ri=20140914=hae5d5c5_1006
  - m4rie=20200125=h051dbe0_0
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib-base=3.10.3=py312hd3ec401_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - maxima=5.47.0=h75482ee_3
  - memory-allocator=0.1.3=py312h66e93f0_1
  - metis=5.1.0=hd0bcaf9_1007
  - mistune=3.1.3=pyh29332c3_0
  - mpc=1.3.1=h24ddda3_1
  - mpfi=1.5.4=h9f54685_1001
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nauty=2.8.9=hb9d3cd8_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - ntl=11.4.3=hef3c4d3_1
  - numpy=2.3.0=py312h6cf2f7f_0
  - openblas=0.3.30=pthreads_h6ec200e_0
  - openjdk=23.0.2=h53dfc1b_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - palp=2.20=h36c2ea0_0
  - pandoc=3.7.0.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h9ac818e_1
  - pari=2.17.2=ha40142e_4_pthread
  - pari-galdata=0.0.20180411=0
  - pari-seadata-small=0.0.20090618=0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py312h80c1187_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - pkg-config=0.29.2=h4bc722e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_5
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - planarity=3.0.2.0=hd590300_0
  - platformdirs=4.3.8=pyhe01879c_0
  - ply=3.11=pyhd8ed1ab_3
  - ppl=1.2=h6ec01c2_1006
  - pplpy=0.8.9=py312h7383a07_2
  - primecount=7.14=h530483c_0
  - primecountpy=0.1.0=py312h68727a3_5
  - primesieve=12.4=he02047a_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lrcalc=2.1=py312h2ec8cdc_7
  - python_abi=3.12=7_cp312
  - pythran=0.17.0=pyh47d16e9_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - pyzmq=27.0.0=py312hbf22597_0
  - qd=2.3.22=h2cc385e_1004
  - qhull=2020.2=h434a139_5
  - r-base=4.3.3=h65010dc_18
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.25.1=py312h680f630_0
  - rpy2=3.5.11=py312r43hc7c0aa3_3
  - rubiks=20070912=h58526e2_1001
  - rw=0.9=hd590300_2
  - sage=10.6=hd8ed1ab_0
  - sagelib=10.6=py312h047bf7c_1
  - sagemath-db-combinatorial-designs=20140630=1
  - sagemath-db-elliptic-curves=0.8.1=hecc5488_0
  - sagemath-db-graphs=20210214=hd8ed1ab_0
  - sagemath-db-polytopes=20170220=1
  - sagetex=3.6.1=pyhd8ed1ab_1
  - scipy=1.16.0=py312hf734454_0
  - sed=4.9=h6688a6e_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - simplegeneric=0.8.1=pyhd8ed1ab_2
  - singular=4.4.1=h7ee4ccf_1
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlite=3.50.2=hb7a22d2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - suitesparse=7.10.1=ha0f6916_7100102
  - symmetrica=3.0.1=hcb278e6_0
  - sympow=2.023.6=h3028977_4
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.17=h0157908_18
  - tachyon=0.99b6=hba7d16a_1002
  - terminado=0.18.1=pyh0d859eb_0
  - three.js=122=hd8ed1ab_2
  - threejs-sage=122=hd8ed1ab_2
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py312h66e93f0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3=py312h7900ff3_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zn_poly=0.9.2=h9202a9a_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.8.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - backrefs==5.9
      - boto3==1.38.46
      - botocore==1.38.46
      - calt-x==0.2.0
      - click==8.2.1
      - docstring-parser==0.16
      - filelock==3.18.0
      - fsspec==2025.5.1
      - ghp-import==2.1.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - griffe==1.7.3
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpx-sse==0.4.1
      - huggingface-hub==0.33.1
      - jmespath==1.0.1
      - joblib==1.5.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markdownify==1.1.0
      - mcp==1.10.1
      - mdformat==0.7.22
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mike==2.1.3
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.2
      - mkdocs-get-deps==0.2.0
      - mkdocs-llmstxt==0.2.0
      - mkdocs-macros-plugin==1.3.7
      - mkdocs-material==9.6.14
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.29.1
      - mkdocstrings-python==1.16.12
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opentelemetry-api==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - paginate==0.5.7
      - pathspec==0.12.1
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pymdown-extensions==10.16
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml-env-tag==1.1
      - regex==2024.11.6
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - sentry-sdk==2.32.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sse-starlette==2.3.6
      - starlette==0.47.1
      - strands-agents==0.1.9
      - super-collections==0.5.3
      - termcolor==3.1.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.0
      - triton==3.3.1
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - verspec==0.1.0
      - wandb==0.20.1
      - watchdog==6.0.0
prefix: /home/sugarl/anaconda3/envs/sage-env
